

[defaults]
server = "0.0.0.0"
port = 80
path = "/github-webhooks"
type = "github"
branch = "main"


[repos.repo1]
server = "0.0.0.0"
port = 80
path = "/webhooks"
type = "github"
branch = "main"
url = ""
remote = "origin"
root_path = "/home/wwwroot/repo1"
updates = ["git pull"]
commands = ["echo 'hello world'"]
